import os
import logging
import traceback

import streamlit as st
from langchain_ollama import OllamaEmbeddings, OllamaLLM
from langchain_chroma import Chroma
from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s"
)
logger = logging.getLogger(__name__)

# ── Config ─────────────────────────────────────────────────
CHROMA_PATH = "chroma_db"
EMBED_MODEL  = "nomic-embed-text"
LLM_MODEL    = "llama3"

# ── Page setup ─────────────────────────────────────────────
st.set_page_config(
    page_title="DPGU Billing Assistant",
    page_icon="🔌",
    layout="centered"
)

# ── Sidebar ────────────────────────────────────────────────
with st.sidebar:
    st.image("https://img.icons8.com/color/96/electricity.png", width=80)
    st.title("DPGU Assistant")
    st.markdown("**Deccan Power & Gas Utilities Ltd**")
    st.markdown("---")

    # 🔥 LLM Toggle
    st.markdown("### ⚙️ Mode Settings")
    llm_enabled = st.toggle("🧠 Enable LLM (llama3)", value=True)

    if llm_enabled:
        st.success("🟢 LLM ON — llama3 generating answers")
    else:
        st.warning("🟡 LLM OFF — showing raw document chunks only")

    st.markdown("---")
    st.markdown("💡 Ask me anything about:")
    st.markdown("- Electricity & gas tariffs")
    st.markdown("- Bill calculations")
    st.markdown("- Payment options")
    st.markdown("- Outage reporting")
    st.markdown("- Meter issues")
    st.markdown("---")
    st.markdown("🤖 Powered by **llama3** via Ollama")
    st.markdown("🗄️ Knowledge base: **ChromaDB**")
    st.markdown("⚡ Running **100% locally**")
    st.markdown("---")
    if st.button("🗑️ Clear Chat"):
        st.session_state.messages = []
        st.rerun()

# ── Load embeddings and vectorstore (always needed) ────────
@st.cache_resource
def load_vectorstore():
    try:
        embeddings = OllamaEmbeddings(model=EMBED_MODEL)
        vectorstore = Chroma(
            persist_directory=CHROMA_PATH,
            embedding_function=embeddings
        )
        return vectorstore
    except Exception as exc:
        logger.error("Failed to load vectorstore: %s", exc)
        raise ConnectionError(
            f"Could not connect to ChromaDB at '{CHROMA_PATH}' "
            f"(embed model='{EMBED_MODEL}'). Is Ollama running? "
            f"Error: {exc}"
        ) from exc

# ── Load RAG chain (only when LLM is ON) ───────────────────
@st.cache_resource
def load_rag_chain():
    vectorstore = load_vectorstore()
    retriever = vectorstore.as_retriever(search_kwargs={"k": 3})

    try:
        llm = OllamaLLM(model=LLM_MODEL)
    except Exception as exc:
        logger.error("Failed to load LLM: %s", exc)
        raise ConnectionError(
            f"Could not load LLM model '{LLM_MODEL}' via Ollama. "
            f"Is Ollama running and the model pulled? Error: {exc}"
        ) from exc

    prompt = PromptTemplate.from_template("""
You are a helpful customer service assistant for Deccan Power & Gas Utilities Ltd.
Answer the customer's question using ONLY the context provided below.
Be concise, friendly and professional.
If the answer is not in the context, say "I'm sorry, I don't have that information.
Please contact our helpline at 1800-XXX-XXXX for assistance."

Context:
{context}

Customer Question: {question}

Answer:""")

    def format_docs(docs):
        return "\n\n".join(doc.page_content for doc in docs)

    chain = (
        {"context": retriever | format_docs, "question": RunnablePassthrough()}
        | prompt
        | llm
        | StrOutputParser()
    )
    return chain

# ── Main UI ────────────────────────────────────────────────
st.title("🔌 Utility Billing Assistant")
if llm_enabled:
    st.markdown("🧠 **LLM Mode** — Answers generated by llama3 from your documents.")
else:
    st.markdown("📄 **Raw Retrieval Mode** — Showing matching document chunks directly.")
st.markdown("---")

# ── Chat history ───────────────────────────────────────────
if "messages" not in st.session_state:
    st.session_state.messages = []
    st.session_state.messages.append({
        "role": "assistant",
        "content": "Hello! 👋 I'm your Deccan Power & Gas Utilities billing assistant. How can I help you today?"
    })

# Display chat history
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# ── Chat input ─────────────────────────────────────────────
if question := st.chat_input("Type your question here..."):

    # Show user message
    st.session_state.messages.append({"role": "user", "content": question})
    with st.chat_message("user"):
        st.markdown(question)

    # Generate answer
    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            try:
                if llm_enabled:
                    # ── LLM ON: full RAG answer ────────────────
                    rag_chain = load_rag_chain()
                    answer = rag_chain.invoke(question)

                else:
                    # ── LLM OFF: raw chunks only ───────────────
                    vectorstore = load_vectorstore()
                    docs = vectorstore.similarity_search(question, k=3)
                    answer = "📄 **Raw document chunks retrieved:**\n\n"
                    for i, doc in enumerate(docs):
                        src = doc.metadata.get('source', 'Unknown')
                        src = os.path.basename(src)
                        answer += f"**Chunk {i+1}** — `{src}`\n"
                        answer += f"{doc.page_content}\n\n---\n\n"

                st.markdown(answer)
                st.session_state.messages.append({
                    "role": "assistant",
                    "content": answer
                })

            except ConnectionError as exc:
                error_msg = (
                    f"⚠️ **Connection error:** {exc}\n\n"
                    "Please make sure Ollama is running and the required "
                    "models are pulled (`ollama pull llama3` / "
                    "`ollama pull nomic-embed-text`)."
                )
                logger.error("Connection error during query: %s", exc)
                st.error(error_msg)
                st.session_state.messages.append({
                    "role": "assistant",
                    "content": error_msg
                })

            except Exception as exc:
                error_msg = f"⚠️ **Unexpected error:** {exc}"
                logger.error(
                    "Unexpected error during query:\n%s",
                    traceback.format_exc()
                )
                st.error(error_msg)
                st.session_state.messages.append({
                    "role": "assistant",
                    "content": error_msg
                })
