import os

import streamlit as st

from app.config import LLM_MODEL
from app.shared import get_vectorstore, build_rag_chain

# ── Page setup ─────────────────────────────────────────────
st.set_page_config(
    page_title="DPGU Billing Assistant",
    page_icon="🔌",
    layout="centered"
)

# ── Sidebar ────────────────────────────────────────────────
with st.sidebar:
    st.image("https://img.icons8.com/color/96/electricity.png", width=80)
    st.title("DPGU Assistant")
    st.markdown("**Deccan Power & Gas Utilities Ltd**")
    st.markdown("---")

    # 🔥 LLM Toggle
    st.markdown("### ⚙️ Mode Settings")
    llm_enabled = st.toggle("🧠 Enable LLM (llama3)", value=True)

    if llm_enabled:
        st.success("🟢 LLM ON — llama3 generating answers")
    else:
        st.warning("🟡 LLM OFF — showing raw document chunks only")

    st.markdown("---")
    st.markdown("💡 Ask me anything about:")
    st.markdown("- Electricity & gas tariffs")
    st.markdown("- Bill calculations")
    st.markdown("- Payment options")
    st.markdown("- Outage reporting")
    st.markdown("- Meter issues")
    st.markdown("---")
    st.markdown(f"🤖 Powered by **{LLM_MODEL}** via Ollama")
    st.markdown("🗄️ Knowledge base: **ChromaDB**")
    st.markdown("⚡ Running **100% locally**")
    st.markdown("---")
    if st.button("🗑️ Clear Chat"):
        st.session_state.messages = []
        st.rerun()

# ── Load embeddings and vectorstore (always needed) ────────
@st.cache_resource
def _load_vectorstore():
    return get_vectorstore()

# ── Load RAG chain (only when LLM is ON) ───────────────────
@st.cache_resource
def _load_rag_chain():
    return build_rag_chain(_load_vectorstore())

# ── Main UI ────────────────────────────────────────────────
st.title("🔌 Utility Billing Assistant")
if llm_enabled:
    st.markdown("🧠 **LLM Mode** — Answers generated by llama3 from your documents.")
else:
    st.markdown("📄 **Raw Retrieval Mode** — Showing matching document chunks directly.")
st.markdown("---")

# ── Chat history ───────────────────────────────────────────
if "messages" not in st.session_state:
    st.session_state.messages = []
    st.session_state.messages.append({
        "role": "assistant",
        "content": "Hello! 👋 I'm your Deccan Power & Gas Utilities billing assistant. How can I help you today?"
    })

# Display chat history
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# ── Chat input ─────────────────────────────────────────────
if question := st.chat_input("Type your question here..."):

    # Show user message
    st.session_state.messages.append({"role": "user", "content": question})
    with st.chat_message("user"):
        st.markdown(question)

    # Generate answer
    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            try:
                if llm_enabled:
                    # ── LLM ON: full RAG answer ────────────────
                    rag_chain = _load_rag_chain()
                    answer = rag_chain.invoke(question)

                else:
                    # ── LLM OFF: raw chunks only ───────────────
                    vectorstore = _load_vectorstore()
                    docs = vectorstore.similarity_search(question, k=3)
                    answer = "📄 **Raw document chunks retrieved:**\n\n"
                    for i, doc in enumerate(docs):
                        src = doc.metadata.get('source', 'Unknown')
                        src = os.path.basename(src)
                        answer += f"**Chunk {i+1}** — `{src}`\n"
                        answer += f"{doc.page_content}\n\n---\n\n"

                st.markdown(answer)
                st.session_state.messages.append({
                    "role": "assistant",
                    "content": answer
                })

            except Exception as e:
                st.error(f"⚠️ Error: {str(e)}")
